---
- name: Remove mariadb-server and python3-mysql when host is CentOS8
  hosts: all
  become: True
  tasks:
    - name: Stop mariadb.service
      systemd:
        name: mariadb
        state: stopped
        enabled: no
        masked: no
      when: ansible_distribution_major_version == "8"
    - name: Remove MariaDB
      yum:
        name: mariadb-server
        state: absent 
      when: ansible_distribution_major_version == "8"
    - name: Remove Python3-MySQL
      yum:
        name: python3-mysql
        state: absent
      when: ansible_distribution_major_version == "8"
    

